config/routes.rb
 Rails.application.routes.draw do
  
  #get 'controller(/:action(/:id))(.:format)'
  #match ':controller(/:action(/:id))(.:format)', via: [:get, :post] 
  
  resources :items do
    get :upvote, on: :member
    # on: :member  -  Это означает, что метод upvote будет доступен для всех item.id
    # :member - значит, что применяется к конкретому ресурсу
    get :expensive, on: :collection
    # Благодаря :collection мы можем в адресной строке прописать: ../items/expensive
    # :collection - применяется ко всей коллекции.
  end
  #передаем блок, внутри которого объясним нашему приложению, 
  #  ,что экшн upvote должен быть доступен для ресурса items

end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord

  belongs_to :user

end

app/models/item.rb
class Item < ApplicationRecord
  validates :price, { numericality: { greater_than: 0, allow_nil: true } }
  # валидация :имя_поля, (передаем ХЭШ, состоящий из цены { Больше чем 0, может быть true)
  validates :name, { presence: true }

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord

  attr_accessor :login
  # Нужно, чтобы при создании пользователя мы могли указывать его login
  
  has_one :cart    
  has_many :orders
  # !!! используется множ. число, т.к. has_many !!!

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :null_session

  private

    def render_403   
    # Если не явл. админом - тогда высвечиваем эту стр. 
      render file: "public/403.html", status: 403
    end

    def render_404    
    # Если ошибка
      render file: "public/404.html", status: 404
    end

     def check_if_admin
      render_403 unless params[:admin]
      # render text: "Access denied", status: 403 unless current_user.admin == true
      # так бы прописали в настоящем приложеннии, а пока только так:
    end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_filter :find_item, only: [:show, :edit, :update, :destroy, :upvote ]
  # есть ещё after_filter, но чаще используется этот
  # фильтру передаем название метода:  :find_item
  # и указываем, перед какими экшенами нужно выполнить метод:  only: [:show, :edit,...]
  before_filter :check_if_admin, only: [:edit, :update, :new, :destroy]
  # Ограничение доступа для простых пользователей. (Могут посетить только index и show)


  def index
    @items = Item.all
    #render "items/index"  -  так не прописываем, т.к. рельсы автоматически это делает.   
  end

  # Экшен для Read
  # /items/new GET
  def show
    # Находим наш товар в БД
    unless @item
      # Изменим так, потому что переменная @item - это инстансная переменнная и т.к. мы её
      # инициализировали в методе find_item она уже будет доступна.
      render text: "Page not found", status: 404
    end
  end

  # Также рэндит форму и отправляет в Create
  # /items/new GET
  def new    
    # Экшн new будет рэндерить шаблон new.html.erb,
    # ,после чего форма шаблона будет отправляться в экшн create
    @item = Item.new
    # Чтобы входные данные не менялись, если не проходит валидацию.
  end

  # Экшн для Create
  # /items POST
  # POST запросы отличаются тем, что в строке адреса их невидно.
  def create
    #render text: params.inspect   
    @item = Item.create(items_params)
    if @item.errors.empty?
      # Проверяем, сохранён ли наш объект без ошибок => отправляем на информацию об объекте
      redirect_to item_path(@item)
    else
      render "new"
      # иначе возвращаем заново на создание объекта
    end
  end

  # Метод Edit будет рэндорить в браузер форму, которая будет отправлять в Update
  # /items/1/edit GET
  def edit
  end

  # Экшн для Update
  # /items/1 PUT
  def update
    @item.update_attributes(items_params)
    # Обновляет данные @item
    if @item.errors.empty?
      # Проверяем, сохранён ли наш объект без ошибок => отправляем на информацию об объекте
      redirect_to item_path(@item)
    else
      render "edit"
      # иначе возвращаем заново на создание объекта
    end
  end

  # Экшн для Destroy
  # items/1 DELETE
  # обратите внимание: метод называется DELETE, a экшн - destroy
  def destroy
    @item.destroy
    # используя метод destroy на объекте класса item для удаления
    redirect_to action: "index"
    # После удаления, обновляем
  end


  def upvote    
    @item.increment!(:votes_count)
    # Обновит значение атрибутов :votes_count, увеличив его на 1 и сохранит в б.д.
    redirect_to action: :index 
    # Редирект на список всез товаров
  end


  def expensive
  # Экшн, который показывает только те товары, стоимость которых больше 1000 рублей.
    @items = Item.where("price > 1000")
    render "index"
    # Если бы не указали render, то был бы вызван шаблон expensive.html.erb, которого нет.
  end


  private
  # Все неприватные методы являются экшенами, а метод find_item - не является экшеном.
  # Метод find_item - является before фильтром.

    def find_item
      @item = Item.where(id: params[:id]).first
      # находим товар, с которым будем работать
      render_404 unless @item
    end


    def items_params
     #params.require(:item).permit(:name, :price, :description, :real, :weight)
     params.require(:item).permit!
     #      требует       запрос атрибутов, которые можно редактировать
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<h1>Edit new item</h1>

<%= form_for @item do |f| %>
<! Чтобы создать нашу форму, мы воспользуемся метоодом form_for, передаем ему объект Item.new
   т.е. form_for знает, что для этого объекта мы создаем форму. 
   * C помощью @item все поля будут уже заполнены.>

	<p>Цена: <br/><%= f.text_field :price %></p>
  <! Вывод текста с помощью .text_field>
	<p>Название: <br/><%= f.text_field :name %></p>
	<p>Описание: <br/><%= f.text_field :description %></p>
	<p>Вес: <br/><%= f.text_field :weight %></p>
	
	<p><%= f.submit "Сохранить товар" %></p>
  <! Создаем кнопку с помощью .submit>

<% end %>
<! завершаем наш блок>

app/views/items/index.html.erb
<h1>Items</h1>

<% if @items.empty? %>
  <b>No items in store</b>
<% else %>
<table>
  <tr>
    <th>item id</th>
    <th>Name</th>
    <th>Price</th>
    <th></th>
  </tr>

  <% @items.each do |i| %>

    <tr>
      <td><%= i.id %></td>
      <td><%= link_to i.name, item_path(i) %></td>
      <td><%= i.price %> руб.</td>
      <td><%= link_to "Удалить", i, method: :delete,  data: {confirm: "Точно удалить?"} %></td>
      <!# Чтобы сделать именно dekete запрос!!! смотрим в gemfile: 
        #gem 'jquery-rails' - должна быть раскомментирована
        #тогда образуется особая ссылка!, используя java-script>
      <!# Чтобы избежать случайного нажатия, должны будем подтвердить, с помощью:
        # data: {confirm: "Точно удалить?"}  >
      <td>Рейтинг: <%= i.votes_count %>, <%= link_to "+", upvote_item_path(i) %></td>
    </tr>

  <% end %>

</table>

<% end %>

app/views/items/new.html.erb
<h1>Create new item</h1>

<%= form_for @item do |f| %>
<! Чтобы создать нашу форму, мы воспользуемся метоодом form_for, передаем ему объект Item.new
   т.е. form_for знает, что для этого объекта мы создаем форму. >

	<p>Цена: <br/><%= f.text_field :price %></p>
  <! Вывод текста с помощью .text_field>
	<p>Название: <br/><%= f.text_field :name %></p>
	<p>Описание: <br/><%= f.text_field :description %></p>
	<p>Вес: <br/><%= f.text_field :weight %></p>
	
	<p><%= f.submit "Создать товар" %></p>
  <! Создаем кнопку с помощью .submit>

<% end %>
<! завершаем наш блок>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>

<ul>
  <li><%= @item.price %>руб.</li>
  <li><%=	@item.description %></li>
  <li>Вес: <%= @item.weight %>кг.</li>>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store5</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>